import type { Novel, Chapter, Character } from '@/types';

export const sampleNovels: Novel[] = [
  {
    id: 'novel-1',
    title: '修仙之路',
    genre: 'xuanhuan',
    theme: '修仙',
    targetChapters: 200,
    writtenChapters: 50,
    wordCount: 150000,
    status: 'writing',
    workflowStatus: 'writing',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-09T15:30:00Z',
    description: '一个普通少年的修仙之旅，历经磨难终成大道',
    outline: '主角林凡是一个普通山村少年，意外获得上古传承，踏上修仙之路...',
  },
  {
    id: 'novel-2',
    title: '都市精英',
    genre: 'dushi',
    theme: '职场',
    targetChapters: 100,
    writtenChapters: 100,
    wordCount: 300000,
    status: 'published',
    workflowStatus: 'published',
    createdAt: '2026-02-15T08:00:00Z',
    updatedAt: '2026-03-05T20:00:00Z',
    description: '都市职场励志故事，小人物逆袭成为行业精英',
    outline: '主角张明从底层销售做起，凭借智慧和努力，一步步爬到公司高层...',
  },
  {
    id: 'novel-3',
    title: '星际迷航',
    genre: 'kehuan',
    theme: '太空探险',
    targetChapters: 150,
    writtenChapters: 30,
    wordCount: 90000,
    status: 'reviewing',
    workflowStatus: 'ai_review',
    createdAt: '2026-03-05T12:00:00Z',
    updatedAt: '2026-03-08T18:00:00Z',
    description: '人类首次深空探索任务，发现未知文明',
    outline: '2150年，人类首次派出深空探索舰队，在仙女座发现了远古文明遗迹...',
  },
  {
    id: 'novel-4',
    title: '缘定三生',
    genre: 'yanqing',
    theme: '古风言情',
    targetChapters: 80,
    writtenChapters: 0,
    wordCount: 0,
    status: 'todo',
    workflowStatus: 'outline',
    createdAt: '2026-03-09T10:00:00Z',
    updatedAt: '2026-03-09T10:00:00Z',
    description: '三生三世的爱情故事，跨越时空的缘分',
    outline: '待生成...',
  },
  {
    id: 'novel-5',
    title: '机甲风暴',
    genre: 'kehuan',
    theme: '机甲战斗',
    targetChapters: 120,
    writtenChapters: 60,
    wordCount: 180000,
    status: 'reviewing',
    workflowStatus: 'human_finalization',
    createdAt: '2026-02-20T14:00:00Z',
    updatedAt: '2026-03-10T09:00:00Z',
    description: '未来世界，人类驾驶机甲抵御外星入侵',
    outline: '2200年，外星种族入侵地球，人类最后的希望是机甲战士...',
  },
];

export const sampleChapters: Chapter[] = [
  {
    id: 'chapter-1',
    novelId: 'novel-1',
    number: 1,
    title: '山村少年',
    content: '青云山脉深处，有一个名为青溪村的小村庄。村子里住着几十户人家，都以采药为生...\n\n林凡今年十六岁，是村里唯一的孤儿。父母在他三岁那年进山采药，再也没有回来...',
    wordCount: 3200,
    status: 'finalized',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-02T15:00:00Z',
  },
  {
    id: 'chapter-2',
    novelId: 'novel-1',
    number: 2,
    title: '上古传承',
    content: '那天，林凡像往常一样进山采药。一场突如其来的暴雨让他躲进了一个隐蔽的山洞...\n\n山洞深处，一块古朴的玉佩散发着淡淡的光芒...',
    wordCount: 3500,
    status: 'finalized',
    createdAt: '2026-03-02T16:00:00Z',
    updatedAt: '2026-03-03T10:00:00Z',
  },
  {
    id: 'chapter-3',
    novelId: 'novel-1',
    number: 3,
    title: '踏入仙途',
    content: '玉佩中蕴含着一部上古功法——《太虚诀》。林凡按照功法指引，开始感应天地灵气...',
    wordCount: 2800,
    status: 'reviewing',
    createdAt: '2026-03-03T11:00:00Z',
    updatedAt: '2026-03-03T18:00:00Z',
  },
];

export const sampleCharacters: Character[] = [
  {
    id: 'char-1',
    novelId: 'novel-1',
    name: '林凡',
    role: 'protagonist',
    description: '十六岁少年，青溪村孤儿，性格坚韧不拔，心地善良',
    traits: ['坚韧', '善良', '聪明', '勤奋'],
  },
  {
    id: 'char-2',
    novelId: 'novel-1',
    name: '苏婉儿',
    role: 'supporting',
    description: '青云宗宗主之女，天赋异禀，与林凡有着不解之缘',
    traits: ['温柔', '高傲', '聪慧'],
  },
  {
    id: 'char-3',
    novelId: 'novel-1',
    name: '魔尊血煞',
    role: 'antagonist',
    description: '上古魔道巨擘，被封印万年，企图重临天下',
    traits: ['残忍', '狡诈', '强大'],
  },
];
